Chap01 Ex2a
ImperialCollegeLondon/m1fexplained pull request #6
Opened 2022-07-25 07:24 UTC by thefundamentaltheor3m

Long proof that can be shortened… any suggestions would be appreciated

2022-07-26 17:31 UTC, kbuzzard requested changes
Thanks a lot! My main comment is to factor out the lemma that D={0} rather than proving it twice.

2022-07-26 17:31 UTC, kbuzzard commented on src/chapter01/exercises/exercise02.lean
> +    -- Any way I can get this hypothesis from the previous proof?
No you can't get it from the previous proof. Proofs are erased after being checked. So what you should do is to make a new lemma saying D = {0} and prove it before part_a. Then you'll be able to use the lemma in both part a and part b.

2022-07-26 17:31 UTC, kbuzzard commented on src/chapter01/exercises/exercise02.lean
> +      simp at hx,
You don't need to do this `simp` call, it doesn't actually do much. Use `squeeze_simp` to see what it's doing, but it's just changing x^2<1 to |x|<1 and then rearranging stuff. I would put this off until later.

2022-07-26 17:31 UTC, kbuzzard commented on src/chapter01/exercises/exercise02.lean
> +      simp,
Don't do non-terminal `simp`s. Use `squeeze_simp` to find out the name of the lemma or lemmas being used, and then rewrite them explicitly.

2022-07-26 17:31 UTC, kbuzzard commented on src/chapter01/exercises/exercise02.lean
> +      cases hl with a ha,
Don't do cases, cases; use `rcases` to take the term apart all in one go.

2022-07-26 17:31 UTC, kbuzzard commented on src/chapter01/exercises/exercise02.lean
> +      rw ha,
Don't be rewriting `ha` everywhere. Use the `rcases rfl` trick to *define* `x` to be `\u a`.

2022-07-28 06:38 UTC, thefundamentaltheor3m commented
> Thanks a lot! My main comment is to factor out the lemma that D={0} rather than proving it twice.

Thank you for the suggestions! I'll start working on them right away

2022-07-28 13:08 UTC, kbuzzard commented
Can you remove the three other files in the commit (the binary .DS_store file and the two files from other chapters?)

2022-07-28 16:02 UTC, kbuzzard commented
PS another UG sniped your part (a)!

2022-08-04 11:08 UTC, kbuzzard commented
Someone else now did this problem. Sorry! :-(

2022-08-04 11:08 UTC, closed without merging